-- 表的结构：sline_member --
CREATE TABLE `sline_member` (
  `mid` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `mtype` varchar(20) DEFAULT NULL COMMENT '会员类型(弃用)',
  `nickname` varchar(255) DEFAULT NULL COMMENT '昵称',
  `pwd` char(32) NOT NULL DEFAULT '' COMMENT '密码',
  `truename` varchar(36) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `sex` enum('男','女','保密') NOT NULL DEFAULT '保密' COMMENT '姓名',
  `rank` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '会员等级',
  `money` double(16,2) NOT NULL DEFAULT '0.00' COMMENT '钱包总额',
  `email` char(50) NOT NULL DEFAULT '' COMMENT '邮箱',
  `mobile` varchar(15) NOT NULL DEFAULT '' COMMENT '手机号',
  `jifen` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '积分',
  `litpic` varchar(255) NOT NULL DEFAULT '' COMMENT '会员头像',
  `safequestion` varchar(255) NOT NULL DEFAULT '0' COMMENT '安全问题',
  `safeanswer` char(30) NOT NULL DEFAULT '' COMMENT '安全答案',
  `jointime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '加入时间',
  `joinip` char(16) NOT NULL DEFAULT '' COMMENT '加入ip',
  `logintime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '上次登陆时间',
  `loginip` char(16) NOT NULL DEFAULT '' COMMENT '登陆ip',
  `checkmail` smallint(6) NOT NULL DEFAULT '0' COMMENT 'email是否通过验证',
  `checkphone` int(1) unsigned DEFAULT '0' COMMENT '手机是否验证',
  `province` varchar(50) DEFAULT NULL COMMENT '省份',
  `city` varchar(50) DEFAULT NULL COMMENT '城市',
  `cardid` varchar(20) DEFAULT NULL COMMENT '身份证号',
  `address` varchar(200) DEFAULT NULL COMMENT '地址',
  `postcode` varchar(8) DEFAULT NULL COMMENT '邮政编码',
  `connectid` varchar(255) DEFAULT '' COMMENT '第三方登陆连接id',
  `from` varchar(255) DEFAULT '' COMMENT '新浪/QQ登陆',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `regtype` tinyint(1) DEFAULT '0' COMMENT '注册类型(0为手机，1为邮箱)',
  `constellation` char(3) DEFAULT NULL COMMENT '星座',
  `qq` char(15) DEFAULT NULL COMMENT 'QQ号',
  `signature` varchar(255) DEFAULT NULL COMMENT '个性签名',
  `birth_date` char(10) DEFAULT NULL COMMENT '出生年月',
  `idcard_pic` varchar(255) DEFAULT NULL COMMENT '身份证照片url地址',
  `verifystatus` tinyint(1) DEFAULT '0' COMMENT '实名认证状态，0->未认证，1->审核中,2->通过,3->未通过',
  `wechat` char(50) DEFAULT NULL COMMENT '微信号',
  `native_place` char(30) DEFAULT NULL COMMENT '籍贯',
  `money_frozen` double(15,2) DEFAULT '0.00' COMMENT '冻结金额',
  `virtual` int(2) DEFAULT '1' COMMENT '是否为虚拟用户 1普通用户 2虚拟用户',
  `reg_from` int(2) DEFAULT NULL COMMENT '默认null:未知,0,admin,1,pc;2,mobile;3,wx;4,xcx,',
  `reg_time` int(10) DEFAULT NULL COMMENT '注册时间,默认未知',
  PRIMARY KEY (`mid`),
  KEY `logintime` (`logintime`)
) ENGINE=InnoDB AUTO_INCREMENT=10760 DEFAULT CHARSET=utf8 COMMENT='会员表';-- <xjx> --

